config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'homes/about' => 'homes#about', as:'about'

  resources :users, only: [:edit,:show,:update,:destroy] do
    resources :relationships, only: [:create,:destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :photos , only: [:index,:new,:create,:show,:edit,:update,:destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :photo_comments, only: [:create,:destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :photo_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/photo_comment.rb
class PhotoComment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
validates :comment, length: { minimum: 2, maximum: 50 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :photos, dependent: :destroy
  has_many :photo_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :icon

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id" ,dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true, presence: true

  def owner(account)
    account = User.first
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: [:new,:edit]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resourse)
    photos_path
  end
  def after_sign_out_path_for(resourse)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @photo = Photo.find(params[:photo_id])
    favorite = current_user.favorites.new(photo_id: @photo.id)
    favorite.save
  end

  def destroy
    @photo = Photo.find(params[:photo_id])
    favorite = current_user.favorites.find_by(photo_id: @photo.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/photo_comments_controller.rb
class PhotoCommentsController < ApplicationController

  def create
    photo = Photo.find(params[:photo_id])
    comment = current_user.photo_comments.new(photo_comment_params)
    comment.photo_id = photo.id
    comment.save
    redirect_to photo_path(photo.id)
  end

  def destroy
    PhotoComment.find(params[:id]).destroy
    redirect_to photo_path(params[:photo_id])
  end

  private

  def photo_comment_params
    params.require(:photo_comment).permit(:comment)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :is_matching_login_user, only: [:edit,:update,:new,:create]
  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    photo = Photo.new(photo_params)
    photo.user_id = current_user.id
    photo.save
    redirect_to photos_path

  end

  def show
    @photo = Photo.find(params[:id])
    @photo_comment = PhotoComment.new
    @owner = User.first
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    photo = Photo.find(params[:id])
    photo.update(photo_params)
    redirect_to photos_path
  end

  def destroy
    photo = Photo.find(params[:id])
    photo.destroy
    redirect_to photos_path
  end

  private

  def photo_params
    params.require(:photo).permit(:photo_name,:caption,:photo)
  end

  def is_matching_login_user
    user = User.first
    unless user.id == current_user.id
      redirect_to photos_path
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit,:update]
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(user.id)
  end

  def show
    @user = User.first
    @owner = User.first
  end

  private

  def user_params
    params.require(:user).permit(:name,:introduction,:icon)
  end
  
  def is_matching_login_user
    user = User.first
    unless user.id == current_user.id
      redirect_to photos_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/photo_comments_helper.rb
module PhotoCommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite.html.erb
<% if photo.favorited_by?(current_user) %>
  <%= link_to photo_favorites_path(photo), class:"text-danger", method: :delete, remote: true do %>
    <i class="fas fa-heart"></i> <%= photo.favorites.count %>
  <% end %>
<% else %>
  <%= link_to photo_favorites_path(photo), class:"text-primary", method: :post, remote: true do %>
    <i class="fas fa-heart"></i> <%= photo.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('.favorite_buttons_<%= @photo.id %>').html("<%= j(render "favorites/favorite", photo: @photo) %>");

app/views/favorites/destroy.js.erb
$('.favorite_buttons_<%= @photo.id %>').html("<%= j(render "favorites/favorite", photo: @photo) %>");

app/views/homes/about.html.erb
<div class="bg-dark">
  <div class="container">
    <div class="row">
      <div class="mx-auto my-5">
        <p class="text-light text-center">A good photograph is one that communicates a fact,<br>touches the heart<br>and leaves the viewer a changed person for having seen it.</p>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/zd4Iwdhl5n8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="parallax_box">
  <div class="parallax_content img_bg_01"><h1>Rumika.N</h1></div>
  <div class="parallax_content img_bg_02"><p>Want to photograph this moment that will never come again</p></div>
  <div class="parallax_content img_bg_03"><p>Want to photograph this moment that will never come again</p></div>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3 class="text-light"><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="bg-secondary">
  <div class="container text-light ">
    <div class="row">
      <div class="mx-auto ">
        <p class="py-5">@1975　hello,world first photographer page. Made by Yuna. 2023</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom ">
  <div class="container-fluid">
    <a class="navbar-brand mt-5 pb-5" href="/"><b>TheFirstAppForMyMam</b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controlls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ml-auto mt-5 pb-3">
        <% if user_signed_in? %>
          <li>
            <%= link_to root_path, class: 'nav-link text-light mr-4' do %>
              <i class="fas fa-home"></i> HOME
            <% end %>
          </li>
          <li>
            <%= link_to about_path, class:"nav-link text-light mr-4" do %>
              <i class="fas fa-link"></i> ABOUT
            <% end %>
          </li>
          <li>
            <%= link_to user_path(current_user.id), class:"nav-link text-light mr-4" do %>
              <i class="fab fa-monero"></i> PROFILE
            <% end %>
          </li>
          <li>
            <%= link_to photos_path, class:"nav-link text-light mr-4" do %>
              <i class="fas fa-images"></i> PHOTOGRAPHS
            <% end %>
          </li>
          <% if User.first == current_user %>
            <li>
              <%= link_to new_photo_path, class:"nav-link text-light mr-4" do %>
                <i class="fas fa-plus"></i> CREATE
              <% end %>
            </li>
          <% end %>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light mr-4" do %>
              <i class="fas fa-sign-out-alt"></i> LOG OUT
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path, class: 'nav-link text-light mr-4' do %>
              <i class="fas fa-home"></i> HOME
            <% end %>
          </li>
          <li>
            <%= link_to about_path, class:"nav-link text-light mr-4" do %>
              <i class="fas fa-link"></i> ABOUT
            <% end %>
          </li>
          <li>
            <%= link_to photos_path, class:"nav-link text-light mr-4" do %>
              <i class="fas fa-images"></i> PHOTOGRAPHS
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path, class:"nav-link text-light mr-4" do %>
              <i class="fas fa-user"></i> LOG IN
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path, class:"nav-link text-light mr-4"  do %>
              <i class="fas fa-users"></i> SIGN UP
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstPhotoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1 maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/nav' %>
    </header>
    
    <%= yield %>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/photos/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-6 mx-auto my-5">
      <%= form_with model: @photo, url: photo_path(@photo.id), method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :photo %>
          <%= f.file_field :photo, accept: 'image/*' %>
        </div>
        <div class="form-group">
          <%= f.label :photo_name %>
          <%= f.text_field :photo_name, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :caption %>
          <%= f.text_area :caption, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit class:"btn btn-info form-control" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/photos/index.html.erb
<div class="bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-md-10 mx-auto my-5">
        <h3 class="my-3 text-light mx-auto">Masterpeaces</h3>
        <% @photos.each do |photo| %>
          <%= link_to photo_path(photo.id) do %>
            <%= image_tag photo.photo, size: "280x280", class:"mt-3 ml-2"  %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/photos/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 mx-auto my-5">
      <h4 class="">Create Photo's form</h4>
        <%= form_with model: @photo do |f| %>
          <div class="form-group">
            <h4>Photo</h4>
              <%= f.file_field :photo, accept: "image/*" %>
          </div>
          <div class="form-group">
            <h4>Title</h4>
              <%= f.text_field :photo_name, class:"form-control" %>
          </div>
          <div class="form-group">
            <h4>Caption</h4>
              <%= f.text_area :caption, class:"form-control" %><br />
          </div>
          <div class="form-group">
            <%= f.submit 'Post', class:"btn btn-info form-control" %>
          </div >
        <% end %>
    </div>
  </div>
</div>

app/views/photos/show.html.erb
<div class="bg-dark">
  <div class="container text-light">
    <div class="row">
      <%= render 'layouts/errors', obj: @photo_comment %>
      <div class="col-sm-12 col-md-10 col-lg-10 mx-auto my-5">
        <%= image_tag @photo.photo, size: '920x750' %><br>
          <table class="table text-light my-5">
            <tr>
              <th></th>
              <th>Title</th>
              <th>Caption</th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
            <tr>
              <td></td>
              <td><%= @photo.photo_name %></td>
              <td><%= @photo.caption %></td>
              <% if user_signed_in? %>
                <td class="favorite_buttons_<%= @photo.id %>">
                  <%= render 'favorites/favorite', photo: @photo %>
                </td>
              <% if User.first == current_user %>
                <td>
                  <%= link_to "Edit", edit_photo_path(@photo.id), class:"btn btn-outline-success" %>
                </td>
                <td>
                  <%= link_to "destroy", photo_path(@photo.id), method: :delete, class:"btn btn-outline-danger", data: { confirm: "Are you sure?" } %>
                </td>
              <% end %>
                <td class="follow-ajax">
                  <%= render 'relationships/follow_btn', user: @owner %>
                </td>
              <% end %>
            </tr>
          </table>
      </div>
      <div class="col-sm-12 col-md-10 col-lg-10 mx-auto mb-5">
        <table class="table text-light mb-5">
          <tr>
            <th></th>
            <th>Comment</th>
            <th>User Name</th>
            <th>Date</th>
            <th></th>
          </tr>
          <% @photo.photo_comments.each do |photo_comment| %>
            <tr>
              <td></td>
              <td><%= photo_comment.comment %></td>
              <td><%= photo_comment.user.name %></td>
              <td><%= photo_comment.created_at.strftime('%Y/%m/%d') %></td>
              <td>
                <% if photo_comment.user == current_user %>
                <%= link_to "destroy", photo_photo_comment_path(photo_comment.photo, photo_comment), method: :delete, class:"btn btn-outline-danger" %>
              <% end %>
              </td>
            </tr>
          <% end %>
          <% if user_signed_in? %>
            <%= form_with model:[@photo,@photo_comment] do |f| %>
              <tr>
                <td></td>
                <td colspan="3"><%= f.text_area :comment ,row: '5', placeholder:"Add comments here", class:"form-control my-1" %></td>
                <td></td>
              </tr>
              <tr>
                <td></td>
                <td colspan="3"><%= f.submit class:"btn btn-outline-success form-control mt-2" %></td>
              </tr>
            <% end %>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/relationships/_follow_btn.html.erb
<% if current_user.following?(user) %>
  <%= link_to 'UnSubscribe', user_relationship_path(user.id), method: :delete, class:"btn btn-outline-danger" %>
<% else %>
  <%= link_to 'Subscribe', user_relationships_path(user.id), method: :post, class:"btn btn-outline-info" %>
<% end %>

app/views/relationships/create.js.erb
$(".follow-ajax").html("<%= j(render "relationships/follow_btn", user: @owner) %>");

app/views/relationships/destroy.js.erb
$(".follow-ajax").html("<%= j(render "relationships/follow_btn", user: @owner) %>");

app/views/relationships/followers.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <table class="table">
        <% if @users.exists? %>
        <tr>
          <th></th>
          <th>Name</th>
          <th></th>
          <th>Made an acount</th>
          <th></th>
        </tr>

        <% @users.each do |user| %>
          <tr>
            <td></td>
            <td><%= user.name %></td>
            <td>Follow: <%= user.followings.count %></td>
            <td>Date: <%= user.created_at.strftime('%Y/%m/%d') %></td>
            <td></td>
          </tr>
          <% end %>
        </table>

      <% else %>
       <p>You don't have any Followers...</p>
      <% end %>
    </div>
  </div>
</div>

app/views/relationships/followings.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <% if @users.exists? %>
        <% @users.each do |user| %>
          <table class="table">
            <tr>
              <th></th>
              <th>Name</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
            <tr>
              <td></td>
              <td><%= user.name %></td>
              <td></td>
              <td>Follower: <%= user.followers.count %></td>
              <td></td>
            </tr>
          </table>
        <% end %>
      <% else %>
       <p>You don't have any Followers...</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-6 mx-auto my-5">
      <h3 class="">Edit user's profile</h3>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <%= f.label :icon %>
            <%= f.file_field :icon, accept: 'image/*' %>
        </div>
        <div class="form-group">
          <%= f.label :name %>
            <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction %>
            <%= f.text_area :introduction, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit class:"form-control btn btn-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="bg-dark">
  <div class="container">
    <div class="row">
      <div class="mx-auto text-light text-center">
        <div class="col-md-8 m-5 ">
          <%= image_tag @user.icon, size: '400x400', class:"rounded-circle my-3" %><br>
          <div class="my-2">
            <%= @user.name %><br>
          </div>
          <div class="mb-4">
            <%= @user.introduction %>
          </div>
          Follower: <%= @owner.followers.count %>
          <% if @user == current_user %>
            <%= link_to 'Edit',edit_user_path(@user.id), class:"btn btn-outline-success form-control" %>
            <%= link_to 'Follower', user_followers_path(@user.id), class:"form-control btn btn-outline-info mt-2" %>
          <% else %>
            <div class="follow-ajax">
            <%= render 'relationships/follow_btn', user: @owner %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>